name: Promote to prod
on:
  repository_dispatch:
    types: [cloudsmith-release]

permissions:
  id-token: write
  contents: read

env:
  CLOUDSMITH_SERVICE: gh-actions-gvq7
  CLOUDSMITH_WORKSPACE: cooke-industries
  CLOUDSMITH_DEV_REPOSITORY: test
  CLOUDSMITH_PROD_REPOSITORY: banking-teamx-prod
#testing change here round 3
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Auth to Cloudsmith with OIDC
      uses: cloudsmith-io/cloudsmith-cli-action@v2
      with:
        oidc-namespace: ${{ env.CLOUDSMITH_WORKSPACE }}
        oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE }}
        oidc-auth-only: 'false'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install deps + run tests (promotion gate)
      run: |
        printf 'registry=https://npm.cloudsmith.io/%s/%s/\n' "$CLOUDSMITH_WORKSPACE" "$CLOUDSMITH_DEV_REPOSITORY" > .npmrc
        printf '//npm.cloudsmith.io/%s/%s/:_authToken=%s\n' "$CLOUDSMITH_WORKSPACE" "$CLOUDSMITH_DEV_REPOSITORY" "$CLOUDSMITH_API_KEY" >> .npmrc
        rm -f package-lock.json
        npm install
        npm test

    - name: On pass — copy to prod + tag the prod copy
      run: |
        SLUG=$(cloudsmith ls pkg $CLOUDSMITH_WORKSPACE/$CLOUDSMITH_DEV_REPOSITORY \
          -q "name:node-app-dev" -F json | jq -r '.data[0].slug')
        cloudsmith copy $CLOUDSMITH_WORKSPACE/$CLOUDSMITH_DEV_REPOSITORY/$SLUG $CLOUDSMITH_PROD_REPOSITORY
        PROD_SLUG=$(cloudsmith ls pkg $CLOUDSMITH_WORKSPACE/$CLOUDSMITH_PROD_REPOSITORY \
          -q "name:node-app-dev" -F json | jq -r '.data[0].slug')
        cloudsmith tag add $CLOUDSMITH_WORKSPACE/$CLOUDSMITH_PROD_REPOSITORY/$PROD_SLUG promote
